#!/usr/bin/env bash
# Shared helpers for GitHub pull-request workflow commands.

gt_command=${gt_command:-git-tools}

gt_usage_error() {
  printf '%s: %s\n' "$gt_command" "$*" >&2
  exit 2
}

gt_die() {
  printf '%s: %s\n' "$gt_command" "$*" >&2
  exit 1
}

gt_say() {
  printf '%s: %s\n' "$gt_command" "$*" >&2
}

gt_require_repo() {
  git rev-parse --git-dir >/dev/null 2>&1 ||
    gt_usage_error "not inside a git repository"
  [[ "$(git rev-parse --is-bare-repository)" == "false" ]] ||
    gt_usage_error "bare repositories are not supported"
}

gt_require_clean_worktree() {
  if [[ -n "$(git status --porcelain)" ]]; then
    gt_die "worktree must be clean"
  fi
}

gt_require_gh() {
  command -v gh >/dev/null 2>&1 ||
    gt_usage_error "gh is not installed or not on PATH"
  gh auth status >/dev/null 2>&1 ||
    gt_die "gh is not authenticated"
}

gt_current_branch() {
  git symbolic-ref -q --short HEAD 2>/dev/null ||
    gt_usage_error "detached HEAD is not supported"
}

gt_pr_view_tsv() {
  local target="$1"
  local -a args=(pr view)
  [[ -z "$target" ]] || args+=("$target")

  # Keep field extraction in gh's structured output path. Human PR titles can
  # contain punctuation freely; using tab-separated fields avoids scraping the
  # default presentation output.
  gh "${args[@]}" \
    --json number,state,isDraft,mergeStateStatus,headRefName,baseRefName,url,title \
    --jq '[.number,.state,.isDraft,.mergeStateStatus,.headRefName,.baseRefName,.url,.title] | @tsv'
}

gt_pr_list_open_tsv() {
  gh pr list --state open --limit 200 \
    --json number,state,isDraft,mergeStateStatus,headRefName,baseRefName,url,title \
    --jq '.[] | [.number,.state,.isDraft,.mergeStateStatus,.headRefName,.baseRefName,.url,.title] | @tsv'
}

gt_pr_checks_status() {
  local target="$1"
  local output status
  local -a args=(pr checks)
  # shellcheck disable=SC2016 # `$buckets` is jq state inside gh's --jq filter.
  local check_state_filter='[.[].bucket] as $buckets | if any($buckets[]; . != "pass" and . != "skipping" and . != "fail" and . != "cancel" and . != "pending") then error("unknown check bucket") elif ($buckets | length) == 0 then "none" elif any($buckets[]; . == "fail" or . == "cancel") then "fail" elif any($buckets[]; . == "pending") then "pending" else "pass" end'
  [[ -z "$target" ]] || args+=("$target")

  set +e
  output=$(
    gh "${args[@]}" \
      --json bucket \
      --jq "$check_state_filter" 2>&1
  )
  status=$?
  set -e

  case "$status" in
    0 | 8)
      printf '%s\n' "$output"
      return 0
      ;;
    *)
      case "$output" in
        *"no checks reported"*)
          printf 'none\n'
          return 0
          ;;
      esac
      printf '%s\n' "$output" >&2
      return "$status"
      ;;
  esac
}

gt_checks_ready_state() {
  local state="$1"

  # Keep merge/readiness control flow on a small internal enum generated by
  # `gh --jq`, not on a best-effort parse of rendered JSON. Unknown states fail
  # closed so a GitHub schema/filter change cannot silently approve a PR.
  case "$state" in
    none | fail | pending | pass)
      printf '%s\n' "$state"
      ;;
    *)
      gt_die "could not parse pull request check status"
      ;;
  esac
}

gt_bool() {
  case "$1" in
    true | TRUE | 1) return 0 ;;
    *) return 1 ;;
  esac
}

# @brief Load open PRs once for repeated by-branch lookups.
# Best-effort: GitHub data is optional, so a missing or unauthenticated gh
# leaves GT_PR_AVAILABLE=false and callers fall back to local-only output.
# Sets GT_PR_AVAILABLE and caches records in GT_PR_RECORDS.
gt_pr_load() {
  GT_PR_AVAILABLE=false
  GT_PR_RECORDS=""

  command -v gh >/dev/null 2>&1 || return 0
  gh auth status >/dev/null 2>&1 || return 0

  GT_PR_RECORDS=$(gt_pr_list_open_tsv 2>/dev/null || true)
  GT_PR_AVAILABLE=true
}

# @brief Print the open PR number whose head ref is the given branch.
# Requires a prior gt_pr_load. Returns 1 when no PR matches or PR data is
# unavailable.
gt_pr_number_for_branch() {
  local branch="$1" number head

  [[ "${GT_PR_AVAILABLE:-false}" == true ]] || return 1
  [[ -n "${GT_PR_RECORDS:-}" ]] || return 1

  # gt_pr_list_open_tsv fields: number, state, isDraft, mergeStateStatus,
  # headRefName, then base, url, and title (unused here).
  while IFS=$'\t' read -r number _ _ _ head _; do
    [[ "$head" == "$branch" ]] || continue
    printf '%s\n' "$number"
    return 0
  done <<<"$GT_PR_RECORDS"

  return 1
}
