name: Tests

on:
  pull_request:
  push:
    branches: [master, main]
  schedule:
    - cron: "57 7 * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  shell:
    uses: cgraf78/actions/.github/workflows/shell-ci.yml@8eaac8e384ae89e9c1aaf675dd23689cfe73fa7c
    with:
      matrix-set: full
      profiles: base
      shellcheck-inventory-path: .github/shellcheck-files.txt
      test-command: GIT_TOOLS_SKIP_SHELLCHECK=1 test/run
